name: Deploy to VPS
on:
  push:
    branches: [ "main" ] # O "master", revisa cómo se llama tu rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Creamos la carpeta si no existe
            mkdir -p ~/web-sobre-mi
                        cd ~/web-sobre-mi
                        
                        if [ ! -d ".git" ]; then
                          git clone https://github.com/A-Goffard/Aintzane-Goffard.git .
                        else
                          git fetch origin main
                          git reset --hard origin/main
                        fi
            
            # Reconstruir FORZANDO la invalidación de capas y recreando el contenedor
            docker compose build --no-cache
            docker compose down
            docker compose up -d --remove-orphans
            
            docker image prune -f